version: '3'

services:
  enroll_rpc:
    container_name: enroll_rpc
    build: python/
    image: boriphuth/enroll_rpc
    restart: always
    depends_on:
      - db
    networks:
      - microservice
      - default
      
  db:
    container_name: enroll_mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
      
  pma:
    container_name: enroll_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - webproxy
      - default
    environment:
      - VIRTUAL_HOST=enroll.boriphuth.net
      - LETSENCRYPT_HOST=enroll.boriphuth.net
      - LETSENCRYPT_EMAIL=boriphuth.sa@boriphuth.net
    depends_on:
      - db
    expose:
      - "80"
      
networks:
  default:
    external:
      name: enroll_network
  microservice:
    external:
      name: microservice_network
  webproxy:
    external:
      name: webproxy