version: "3"
services:
  rabbitmq:
    image: lucifer8591/rabbitmq-server:3.7.17
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    networks:
      - webproxy
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
      - VIRTUAL_HOST=rabbitmq.boriphuth.net
      - LETSENCRYPT_HOST=rabbitmq.boriphuth.net
      - LETSENCRYPT_EMAIL=boriphuth.sa@boriphuth.net
networks:
  default:
    external:
      name: microservice_network
  webproxy:
    external:
      name: webproxy