version: '3'

services:
  email_rpc:
    container_name: email_rpc
    build: python/
    image: boriphuth/email_rpc
    restart: always

    networks:
      - microservice
      - default
  
  smtp:
    image: namshi/smtp
    container_name: smtp_relay
    restart: always
    ports:
     - "25:25"
    environment:
     # # MUST start with : e.g RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
     # # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
     # - RELAY_NETWORKS= :192.168.0.0/24
     # # what domains should be accepted to forward to lower distance MX server.
     # - RELAY_DOMAINS= <domain1> : <domain2> : <domain3>
     # # To act as a Gmail relay
     - GMAIL_USER=${RELAY_USERNAME}
     - GMAIL_PASSWORD=${RELAY_PASSWORD}
     # # For use with Amazon SES relay
     # - SES_USER=
     # - SES_PASSWORD=
     # - SES_REGION=
     # # if provided will enable TLS support
     # - KEY_PATH=
     # - CERTIFICATE_PATH=
     # # the outgoing mail hostname
     # - MAILNAME=
     # # set this to any value to disable ipv6
     # - DISABLE_IPV6=
     # # Generic SMTP Relay
     # - SMARTHOST_ADDRESS=${RELAY_HOST}
     # - SMARTHOST_PORT=${RELAY_PORT}
     # - SMARTHOST_USER=${RELAY_USERNAME}
     # - SMARTHOST_PASSWORD=${RELAY_PASSWORD}
     # - SMARTHOST_ALIASES=

networks:
  default:
    external:
      name: email_network
  microservice:
    external:
      name: microservice_network