version: '3'

services:
  email_rpc:
    container_name: email_rpc
    build: python/
    image: boriphuth/email_rpc
    restart: always

    networks:
      - microservice
      - default

  smtp:
    container_name: email_smtp
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: ${RELAY_HOST}
      RELAY_PORT: ${RELAY_PORT}
      RELAY_USERNAME: ${RELAY_USERNAME}
      RELAY_PASSWORD: ${RELAY_PASSWORD}

networks:
  default:
    external:
      name: email_network
  microservice:
    external:
      name: microservice_network