version: "2"

services:
  portainer:
    image: portainer/portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.ec2-3-8-185-42.eu-west-2.compute.amazonaws.com
      - LETSENCRYPT_HOST=portainer.ec2-3-8-185-42.eu-west-2.compute.amazonaws.com
      - LETSENCRYPT_EMAIL=boriphuth.sa@gmail.com
    networks:
      - webproxy
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  default:
    external:
      name:
        web_network
  webproxy:
    external:
      name: webproxy

volumes:
  portainer_data: